seed: 42
dry_run: false

dataset:
  root: "/Volumes/satechi/ml_projects/mnist"
  train_images_filename: "train-images-idx3-ubyte.gz"
  train_labels_filename: "train-labels-idx1-ubyte.gz"
  test_images_filename: "t10k-images-idx3-ubyte.gz"
  test_labels_filename: "t10k-labels-idx1-ubyte.gz"

training:
  learning_rate: 0.001
  batch_size: 256
  early_stopping_patience: 20
  num_epochs: 100

  early_stopping: true

scheduler:
  type: ReduceLROnPlateau
  params:
    patience: 5
    factor: 0.5

model:
  dropout: 0.5
  fc_hidden: [128]
  conv_layers:
    - out_channels: 256
      kernel_size: 7
      padding: 0
      pool: 2
      stride: 1
    - out_channels: 32
      kernel_size: 5
      padding: 0
      pool: 2
      stride: 1
