seed: 42
dry_run: false

dataset:
  root: "/Volumes/satechi/ml_projects/cifar"
  num_workers: 0
  pin_memory: false

train_augmentations:
  dataset_augmentations:
    - type: RandomHorizontalFlip
      params:
        p: 0.5
    - type: RandomRotation
      params:
        degrees: [-5.0, 5.0]
    - type: RandomCrop
      params:
        size: 32
        padding: 2
        padding_mode: "reflect"
  dataloader_augmentations:
    - type: CutMix
      params:
        alpha: 0.2
        num_classes: 100
    - type: MixUp
      params:
        alpha: 0.2
        num_classes: 100

training:
  batch_size: 256
  num_epochs: 200
  scheduler_update_freq: step

scheduler:
  type: OneCycleLR
  params:
    max_lr: 1e-2
    pct_start: 0.1

optimizer:
  type: AdamW
  params:
    lr: 1e-3
    weight_decay: 1e-2

early_stopping:
  patience: 30
  min_delta: 0
  higher_is_better: true

model:
  stem:
    conv:
      out_channels: 64
      kernel_size: 3
      padding: 1
      stride: 1
    maxpool: null
    #   kernel_size: 3
    #   stride: 2
    #   padding: 1
  layers:
    - out_channels: 64
      kernel_size: 3
      padding: 1
      stride: 1
      blocks: 3
    - out_channels: 128
      kernel_size: 3
      padding: 1
      stride: 2
      blocks: 2
    - out_channels: 256
      kernel_size: 3
      padding: 1
      stride: 2
      blocks: 2
    - out_channels: 512
      kernel_size: 3
      padding: 1
      stride: 2
      blocks: 2